jobs:
    include:
       - stage: "Static tests"
         name: "Static tests"
         addons:
            sonarcloud:
                 organization: "sgt390-github"
                 token:
                    secure: "$SONAR_TOKEN"
         script: sonar-scanner
       - stage: "Dynamic tests"  
         name: "Unit tests"
         script: skip
       - name: "Integration tests"
         script: skip
       - stage: deploy
         deploy:
               - provider: script
                 script: bash /script/deploy.sh
                 on:
                   branch: develop
               - provider: lambda
               function_name: "megalexa"
               region: "us-east-1"
               role: "arn:aws:iam::401184049861:role/service-role/basicpermission"
               runtime: "nodejs8.10"
               handler_name: "handler"
               zip: "lambda/"
               on:
                  branch: develop
stages:
  - "Static tests"
  - "Dynamic tests"
  - deploy      
#notifications:
#  slack: zerosevengroup:awH2p9uSzEPY9plMSyKBtAHF
